apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-test-load-balancing
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: "load.bar.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-webapp-service
            port:
              number: 80

